#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the countingValleys function below.
def countingValleys(n, s):
    result = 0
    # valley_shape = []
    for i, step in enumerate(s):
        for j in i:
            print(s[:j].count)

            # if s[i] is "U" and :

    # print(valley_shape)
    return result

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input())

    s = input()

    result = countingValleys(n, s)

    fptr.write(str(result) + '\n')

    fptr.close()
